name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Git User Random GPG Key
        uses: iwishiwasaneagle/git-user-random-gpg@v1
        with:
          email: jaisuriya200297@gmail.com
          name: jaisuriya092
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: learning092-admin
          spacename: learning092
          repository: bitbuckettesting
          password: ${{ secrets.BITBUCKET_PASSWORD }}
