
name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Configure Git User (Force Bitbucket User as "learning092-admin")
        run: |
          git config --global user.name "learning092-admin"
          git config --global user.email "200701092@rajalakshmi.edu.in"
          git config --global commit.gpgsign false
          git config --global tag.gpgSign false

      - name: Reformat Git History to Change Committer
        run: |
          git checkout Testbranch
          git commit --amend --no-edit --author="learning092-admin <200701092@rajalakshmi.edu.in>"
          git rebase --root --committer-date-is-author-date
        
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: learning092-admin
          spacename: learning092
          repository: BitbucketTesting
          password: ${{ secrets.BITBUCKET_PASSWORD }}


