name: Sync to Bitbucket

on:
  push:
    branches:
      - main  # Change this to the branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Push to Bitbucket
        run: |
          git clone --mirror https://bitbucket.org/learning092/bitbuckettesting/ bitbucket_repo
          cd bitbucket_repo
          git remote add github-origin https://github.com/jaisuriya97/BitbucketTesting/
          git fetch github-origin
          git push origin --mirror
