name: Mirror to Bitbucket

on:
  push:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      # - name: Set up Git
      #   run: |
      #     git config --global user.email "you@example.com"
      #     git config --global user.name "Your Name"
      
      - name: Mirror to Bitbucket
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: learning092-admin
          spacename: learning092
          repository: bitbuckettesting
          password: ${{ secrets.BITBUCKET_PASSWORD }}

      - name: Push to Bitbucket with no-verify
        run: git push --no-verify
        env:
          BITBUCKET_PASSWORD: ${{ secrets.BITBUCKET_PASSWORD }}
